### ISSUE TITLE
Update user documentation to include DFU

### ISSUE THREAD

**Issue by mbanth** [xmos/host_xvf_control#69]
This issue follows on from issues #64, #65, #67 and #68, and it covers updates to the XVF38xx User Guide.  The documentation includes using the host DFU app to:

- [ ] Upgrade the firmware, and
- [ ] Revert to the Factory firmware image.

It should also include a section on how to detect exceptional cases including:

- [ ] Behaviour during an interrupted upgrade, and
- [ ] Attempts to use an invalid upgrade image.

The exceptional case section must include the requirement for the user to re-boot the device described in [a comment by @lucianomartin in issue 100](https://github.com/xmos/sw_xvf3800/issues/100#issuecomment-1573623486).

**Comment by lucianomartin** [comment]
> @lucianomartin, has this work been done for USB-based DFU?

We did it for the XVF3800 documentation only. I think this issue was intended for the host app documentation, but as we have used the open source dfu-util app so far, this was not necessary. I reckon if we use DFU over HID, we may need a new host app and the relevant documentation should be updated.

**Comment by lucianomartin** [comment]
Re-opening this issue to include an improvement in the firmware. See https://github.com/xmos/fwk_xvf/pull/105
